//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Product
    {
        public int ProductId { get; set; }
        //[Required(ErrorMessage ="Please Enter your Name")]  //ata server side validation er jonno
        //[Display(Name ="Product Name")]
        public string Name { get; set; }
        //[Required(ErrorMessage = "Please Enter Description")]
        //[Display(Name="Product Description")]
        public string Description { get; set; }
    }
}
